=== akhilgupta01/tool.codoogle/codoogle-common-utils/src/main/xsd/codoogle-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.fullgc.com/codoogle/vcs-config/" targetNamespace="http://www.fullgc.com/codoogle/vcs-config/">

	<!-- ************************************************************************************* -->
	<!-- ********************** Version control system related configurations **************** -->
	<!-- ************************************************************************************* -->
	<complexType name="SourceControlSystemType" abstract="true">
		<attribute name="id" type="string"></attribute>
		<attribute name="user" type="string"></attribute>
		<attribute name="password" type="string"></attribute>
	</complexType>

	<complexType name="CVSType">
		<complexContent>
			<extension base="tns:SourceControlSystemType">
				<sequence>
					<element name="hostName" type="string"></element>
					<element name="path" type="string"></element>
				</sequence>
				
			</extension>
		</complexContent>
	</complexType>

	<complexType name="SVNType">
		<complexContent>
			<extension base="tns:SourceControlSystemType"></extension>
		</complexContent>
	</complexType>

	<!-- ************************************************************************************* -->
	<!-- *************************** Call trace configurations ******************************* -->
	<!-- ************************************************************************************* -->
    
    <complexType name="DomainConfigType">
    	<attribute name="domainName" type="string"/>
    	<attribute name="adminHostName" type="string"/>
    	<attribute name="adminPort" type="int"/>
    	<attribute name="userName" type="string"/>
    	<attribute name="password" type="string"/>
    	<attribute name="serverNamePattern" type="string"/>
    </complexType>

    <complexType name="TraceCollectionGroupType">
    	<sequence>
    		<element name="domainConfig" type="tns:DomainConfigType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    	<attribute name="id" type="string"/>
    	<attribute name="indexGroup" type="string"/>
    	<attribute name="threadDumpInterval" type="long"/>
    	<attribute name="totalDuration" type="long"/>
    </complexType>


	<!-- ************************************************************************************* -->
	<!-- *************************** Call index configuration ******************************** -->
	<!-- ************************************************************************************* -->
	<complexType name="CodeIndexConfigType">
		<sequence>
			<element name="checkoutLocation" type="string" maxOccurs="1" minOccurs="1" />
			<element name="ignoredFiles" type="string" maxOccurs="1" minOccurs="0" />			<element name="modulesList" type="tns:ModuleListType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="indexGroup" type="string" use="required"/>
		<attribute name="refreshInterval" type="integer" use="optional"/>
	</complexType>

	<complexType name="CodoogleConfigurationType">
    	<sequence>
    		<element name="baseIndexLocation" type="string"
    			maxOccurs="1" minOccurs="1" />
    		<element name="codeIndexGroups"
    			type="tns:CodeIndexConfigType" maxOccurs="unbounded"
    			minOccurs="0" />
    		<element name="traceCollectionGroups"
    			type="tns:TraceCollectionGroupType" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>

    		<element name="threadDumpConfig"
    			type="tns:ThreadDumpConfigType" maxOccurs="1" minOccurs="0">
    		</element>
    		<element name="sourceControlInfo" type="tns:SourceControlSystemType" maxOccurs="unbounded" minOccurs="0"/>
    	</sequence>
	</complexType>

    <element name="codoogleConfig" type="tns:CodoogleConfigurationType">
    </element>

    <complexType name="ThreadDumpConfigType">
    	<sequence>
    		<element name="includedPatterns" type="tns:IncludedPatterns"></element>
    		<element name="excludedPatterns" type="tns:ExcludedPatterns"></element>
    		<element name="excludedEntryPointPatterns" type="tns:ExcludedEntryPointPatterns"></element>
    	</sequence>
    </complexType>

    <complexType name="IncludedPatterns">
    	<sequence>
    		<element name="include" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <complexType name="ExcludedPatterns">
    	<sequence>
    		<element name="exclude" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <complexType name="ExcludedEntryPointPatterns">
    	<sequence>
    		<element name="excludedEntryPointPattern" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <complexType name="ModuleListType">
    	<sequence>
    		<element name="file" type="string" maxOccurs="1" minOccurs="1"/>
    		<element name="sourceControlId" type="string" maxOccurs="1" minOccurs="1"/>
    		<element name="branch" type="string" maxOccurs="1" minOccurs="1"/>
    	</sequence>
    </complexType>
</schema>

=== akhilgupta01/tool.codoogle/codoogle-gui/src/main/resources/codoogle-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:codoogleConfig 
	xmlns:tns="http://www.fullgc.com/codoogle/vcs-config/" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.fullgc.com/codoogle/vcs-config/ codoogle-config.xsd ">
  
	<baseIndexLocation>/codeExplorer/codoogle/indexes</baseIndexLocation>

	<sourceControlInfo xsi:type="tns:CVSType" id="repo1" user="agupta1" password="password">
		<hostName>cvshost.name</hostName>
		<path>/cvs/repositories/repo1</path>
	</sourceControlInfo>
	
	<codeIndexGroups indexGroup="branch_rel_16_10" refreshInterval="900">
		<checkoutLocation>/codeExplorer/codoogle/sources</checkoutLocation>
		<ignoredFiles>.*\/CVS\/.*</ignoredFiles>
		<modulesList>
			<file>/codeExplorer/codoogle/branch_rel_16_10.txt</file>
			<sourceControlId>repo1</sourceControlId>
			<branch>branch_rel_16_10</branch>
    	</modulesList>
	</codeIndexGroups>

	<codeIndexGroups indexGroup="branch_rel_16_20" refreshInterval="900">
		<checkoutLocation>/codeExplorer/codoogle/sources</checkoutLocation>
		<ignoredFiles>.*\/CVS\/.*</ignoredFiles>
		<modulesList>
			<file>/codeExplorer/codoogle/branch_rel_16_20.txt</file>
			<sourceControlId>repo1</sourceControlId>
			<branch>branch_rel_16_20</branch>
    	</modulesList>
	</codeIndexGroups>

	<traceCollectionGroups id="prd_cbe_cust_servers" indexGroup="PRD" threadDumpInterval="5000" totalDuration="100000">
		<domainConfig adminHostName="adminhost" adminPort="8500" domainName="PRD_CBE_DOMAIN" serverNamePattern="wlsCbeCus.*" userName="uuuuu" password="ppppp" />
	</traceCollectionGroups>

	<threadDumpConfig>
		<includedPatterns>
			<include>com.sun.xml.ws.client.sei.SEIStub.invoke.*</include>
			<include>.*ExecuteThread.*for queue.*</include>
			<include>weblogic.wsee.jaxws.HttpServletAdapter.*</include>
			<include>weblogic.wsee.server.servlet.SoapProcessor.*</include>
			<include>weblogic.webservice.server.servlet.WebServiceServlet.*</include>
		</includedPatterns>
		<excludedPatterns>
			<exclude>.*__WL_invoke.*</exclude>
			<exclude>.*Log4JWatchDog.*</exclude>
			<exclude>.*comm.persistence.*</exclude>
			<exclude>.*comm.integration.*</exclude>
			<exclude>.*j2eeframework.datalayer.dbconnection.*</exclude>
			<exclude>.*j2eeframework.services.logging.*</exclude>
			<exclude>.*utils.*Logger.*</exclude>
			<exclude>.*utils.AppServiceFactory.*</exclude>
			<exclude>.*NinasConnectionFactory.*</exclude>
			<exclude>weblogic.wsee.server.servlet.SoapProcessor.process.*</exclude>
			<exclude>weblogic.wsee.jaxws.HttpServletAdapter.*run.*</exclude>
			<exclude>weblogic.webservice.server.servlet.WebServiceServlet.serverSideInvoke.*</exclude>
			<exclude>.*BusinessExceptionUtils.*</exclude>
			<exclude>.*soa_model.entities.*</exclude>
			<exclude>.*toString.*</exclude>
			<exclude>.*ProxyBindingCalls.*</exclude>
			<exclude>.*makeConnection.*</exclude>
			<exclude>.*RotatingFileWriter.*</exclude>
			<exclude>.*org.apache.log4j.*</exclude>
			<exclude>.*comm.kpi.*</exclude>
			<exclude>.*comm.log.*</exclude>
		</excludedPatterns>
		<excludedEntryPointPatterns>
			<excludedEntryPointPattern>.*srv.common.portal.iacf.*</excludedEntryPointPattern>
			<excludedEntryPointPattern>.*comm.presentation.*</excludedEntryPointPattern>
			<excludedEntryPointPattern>.*pres.common.framework.*</excludedEntryPointPattern>
			<excludedEntryPointPattern>.*j2eeframework.*</excludedEntryPointPattern>
			<excludedEntryPointPattern>weblogic.wsee.jaxws.HttpServletAdapter.*</excludedEntryPointPattern>
			<excludedEntryPointPattern>weblogic.wsee.server.servlet.SoapProcessor.*</excludedEntryPointPattern>
			<excludedEntryPointPattern>weblogic.webservice.server.servlet.WebServiceServlet.*</excludedEntryPointPattern>
		</excludedEntryPointPatterns>
	</threadDumpConfig>
</tns:codoogleConfig>
